language: r
r:
  - release
  - devel
sudo: false
cache: packages
r_build_args: "--resave-data=best"
r_check_args: "--as-cran"
env:
   global:
     - DISPLAY=:99.0

r_github_packages:
  - jimhester/covr
  - trinker/numform
  - trinker/gofastr
  - kbenoit/quanteda
  - thomasp85/ggraph

before_install:
  - sh -e /etc/init.d/xvfb start

after_success:
  - Rscript -e 'covr::coveralls()'
